setup.py: Install SecretStorage 2.x for Python older than 3.5
jaraco/keyring pull request #320
Opened 2018-04-23 21:16 UTC by mitya57

This hack is only needed for pip versions older than 9.
Fixes #301.

@jaraco I have little experience in writing PEP 508 markers, so please review it.

2018-04-23 21:51 UTC, jaraco commented
This looks right to me. The use of a ranged operator in the environment marker (`python_version >=`) means this change won't work without `setuptools >= 17.1`... but that's 16 months earlier than pip 9, so maybe worth the dependency for a while.

2018-04-23 21:53 UTC, jaraco requested changes
The test failure does indicate a regression in the relevant environment (Python 3.6 Linux). That'll need to be addressed. Otherwise, this change seems acceptable.

2018-04-23 22:15 UTC, jafreck commented
This also fixes #321

2018-04-24 06:31 UTC, takluyver commented
The tests are failing with a KeyError, whereas on Python 2 those tests are all skipped. I think this is the relevant bit of code:

https://github.com/jaraco/keyring/blob/1e25fde80b5e45cc25fe3efdf4edded27706578b/keyring/backends/SecretService.py#L36-L41

Somewhere along the stack, the KeyError from getting the environment variable needs to be caught and turned into a SecretServiceNotAvailableException. I'm open to raising a more semantically meaningful exception from Jeepney if that's useful, though of course it wouldn't be the specific secret service exception.

It might also be worth trying to run DBus and a secretstorage server on Travis so that the backend can be tested properly. I see secretstorage already does this:

https://github.com/mitya57/secretstorage/blob/70e723c5ad7964dad6d6f7f962155bc76dd17eee/.travis.yml#L16-L17

2018-04-24 10:04 UTC, cassioiks commented
So, my builds are breaking already due to secretstorage 3.0.0 requirement for Python 3.5+.
Any timeline on when this pull request can be completed?

Btw, thanks @mitya57 for going ahead and creating this PR.

2018-04-24 12:11 UTC, mitya57 commented
With SecretStorage 3.0.1, the issue with KeyError is fixed, so I am merging this now.

@jaraco Do you think it is worth a new release?

2018-04-24 12:11 UTC, merged

2018-04-24 12:26 UTC, jladdjr commented
@mitya57 - a new release would be helpful for our team; currently we're relying on a workaround where we install a downlevel version of secretstorage before installing keyring