Changed importlib_metadata to have requirement for < python 3.10
jaraco/keyring pull request #577
Opened 2022-05-25 00:12 UTC by probro27

Trying to fix the issue #575.
Hope it works!!

2022-05-27 09:50 UTC, mitya57 requested changes
Also please see what I wrote in this comment:
https://github.com/jaraco/keyring/pull/576#pullrequestreview-987281982

2022-05-27 09:50 UTC, mitya57 commented on setup.cfg
> +	importlib_metadata < 3.10; python_version < "3.10"
We should still specify the minimum version of `importlib_metadata`, and I don't see the point of specifying the maximum version (the latest version of backport is 4.x and it should work fine).

2022-05-27 16:54 UTC, probro27 commented on setup.cfg
> +	importlib_metadata < 3.10; python_version < "3.10"
I was just trying to solve the open issue. I'm not super familiar with this. What I got was that importlib_metadata was kind of increasing the dependencies that may not be required for python versions over 3.10. 
If you want I can put importlib_metadata to be compolusory for python >=3.6 and <= 3.10. 
Hope this works out! Just starting out with open source so hoping it's fine.

2022-05-27 17:05 UTC, mitya57 commented on setup.cfg
> +	importlib_metadata < 3.10; python_version < "3.10"
The correct line would be:
```suggestion
	importlib_metadata >= 3.6; python_version < "3.10"
```

This means: require `importlib_metadata` at least 3.6 for Python older than 3.10.

2022-05-27 17:07 UTC, probro27 commented on setup.cfg
> +	importlib_metadata < 3.10; python_version < "3.10"
Oh I understand now! Thank you! I'll commit this suggestion so that it's added to the pull request!
thanks for the tip. First time in open source so was really lost!
Appreciate it!

2022-05-27 17:11 UTC, mitya57 commented on setup.cfg
> +	importlib_metadata < 3.10; python_version < "3.10"
Now please also see this: https://github.com/jaraco/keyring/pull/576#pullrequestreview-987281982

It needs to be replaced in three files: `hook-keyring.backend.py`, `keyring/backend.py`, `tests/test_packaging.py`.

2022-05-27 19:46 UTC, probro27 commented
I have updated the imports as per [#576 (review)](https://github.com/jaraco/keyring/pull/576#pullrequestreview-987281982)
Hope this works!

2022-05-27 20:48 UTC, mitya57 requested changes

2022-05-27 20:48 UTC, mitya57 commented on tests/test_packaging.py
> +    import importlib_metadata as metadataetadata
```suggestion
    import importlib_metadata as metadata
```

2022-05-27 21:10 UTC, mitya57 approved these changes

2022-05-27 21:15 UTC, probro27 commented
Hmm, any idea what might cause the tests to fail? I  didn't change anything that could cause errors. I'll try to investigate. If you find anything, let me know! 
Thanks!

2022-05-27 21:30 UTC, mitya57 commented
So mypy complains about this:
```
______________________________ keyring/backend.py ______________________________
15: error: Name "metadata" already defined (by an import)
___________________________ tests/test_packaging.py ____________________________
4: error: Name "metadata" already defined (by an import)
```

I would simply silence that. Try adding `# type: ignore` comments at the end of line 15 of `keyring/backend.py` and line 4 of `tests/test_packaging.py`.

Like this:
```python
try:
    from importlib import metadata
except ImportError:
    import importlib_metadata as metadata  # type: ignore
```

2022-05-27 21:43 UTC, probro27 commented
Alright I have added that. Thanks for the help! 
Let's hope it works now!

2022-05-28 07:42 UTC, mitya57 commented
I am sorry. It still doesn't work because Python 3.9 and earlier does have `importlib.metadata` available, although it does not support `group` argument, so we can't use it.

Let's try this:

```python
import sys

if sys.version_info >= (3, 10):
    from importlib import metadata
else:
    import importlib_metadata as metadata
```

Add `import sys`

I hope `# type: ignore` won't be needed with this, but let's see.

2022-05-28 18:05 UTC, probro27 commented
I have added the `# type:ignore ` on the imports for now, coz I was getting a linting error when I was not doing that. I hope this works!

2022-05-28 18:15 UTC, probro27 commented
`_________________________________ FLAKE8-check _________________________________
/home/runner/work/keyring/keyring/tests/test_packaging.py:6:42: E261 at least two spaces before inline comment
/home/runner/work/keyring/keyring/tests/test_packaging.py:6:43: E262 inline comment should start with '# '`
Does this seem to be the error?

2022-05-28 18:17 UTC, mitya57 commented
Yes, you need two spaces before `#` and one space after `#`. And please remove commented out code.

2022-05-28 21:56 UTC, probro27 commented
Okay, I have changed the formatting and removed the comments.

2022-05-29 16:04 UTC, mitya57 approved these changes
Yes, now CI finally passes. Thanks!

You have my approval, but let's wait for @jaraco who is the chief maintainer.

2022-06-05 00:33 UTC, jaraco approved these changes
I added a couple of nitpicky changes and a changelog, but this looks good. Thanks for pulling it together!

2022-06-05 00:33 UTC, merged

2022-06-07 23:37 UTC, probro27 commented
Thanks for merging it! 
Glad to be of help :))